# Generated by Django 6.1 on 2026-09-16 14:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('matricula', models.TextField(blank=True)),
                ('idade', models.IntegerField()),
                ('cpf', models.TextField()),
                ('endereco', models.TextField()),
                ('telefone', models.TextField()),
                ('ativo', models.BooleanField()),
                ('data_cadastro', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.TextField()),
                ('nome', models.TextField()),
                ('idade', models.IntegerField()),
                ('endereco', models.TextField()),
                ('telefone', models.IntegerField()),
                ('ativo', models.BooleanField()),
                ('data_cadastro', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turma', models.TextField()),
                ('turno', models.CharField(max_length=10)),
                ('ativo', models.BooleanField()),
                ('data_cadastro', models.DateField(default=django.utils.timezone.now)),
                ('observacao', models.TextField()),
                ('aluno_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema1.aluno')),
                ('professor_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema1.professor')),
            ],
        ),
    ]
