# Generated by Django 6.1 on 2026-09-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_medico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='crm',
            field=models.CharField(max_length=6),
        ),
    ]
