# Generated by Django 6.1 on 2026-09-16 11:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_alter_medico_crm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consulta_nova', models.CharField(default='nova_consulta', max_length=20)),
                ('data_consulta', models.DateTimeField(default=django.utils.timezone.now)),
                ('ativa', models.BooleanField(default=True)),
                ('observacao', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('A', 'Agendada'), ('X', 'Cancelada'), ('C', 'Confirmada'), ('R', 'Realizada')], default='A', max_length=1)),
                ('medico_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.medico')),
                ('paciente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.paciente')),
            ],
        ),
    ]
